uploads = []
outputs = []

[[generated]]
id = "_l24iEz11_b2DY6VxoHBE"
uri = "file://artifacts/united-mechanic/public/hero.png"
type = "image"
title = "Auto shop interior hero"

[[generated]]
id = "F4uwLjmRcUY721BMqps0e"
uri = "file://artifacts/united-mechanic/public/transmission.png"
type = "image"
title = "Mechanic working on transmission"

[[generated]]
id = "vm1kV06JOUUlpkTJ1Ko7W"
uri = "file://artifacts/united-mechanic/public/engine.png"
type = "image"
title = "Open car engine bay"

[[generated]]
id = "u3-UK0ew0fs0PUBX5S9Pq"
uri = "file://artifacts/united-mechanic/public/brakes.png"
type = "image"
title = "Car brakes being serviced"

[[generated]]
id = "wxDHQtVhdwe_tHTHjJsp0"
uri = "file://artifacts/united-mechanic/public/ac-heat.png"
type = "image"
title = "AC heat repair service"

[[generated]]
id = "wDmjduVEhIloJHhmyGq4p"
uri = "file://artifacts/united-mechanic/public/alignment.png"
type = "image"
title = "wheel alignment service"

[[generated]]
id = "2mbtTPX2VyEKo23R0psnp"
uri = "file://artifacts/united-mechanic/public/diesel.png"
type = "image"
title = "diesel engine repair"

[[generated]]
id = "1uYnabBxaPGbQMm09JkGY"
uri = "file://artifacts/united-mechanic/public/electrical.png"
type = "image"
title = "automotive electrical repair"

[[generated]]
id = "UX-QGV8GkeI3oT1gIQfcx"
uri = "file://artifacts/united-mechanic/public/oil-change.png"
type = "image"
title = "oil change service"

[[generated]]
id = "Ma0aSPftHQsf1mD4IQTs3"
uri = "file://artifacts/united-mechanic/public/diagnostics.png"
type = "image"
title = "car diagnostics service"
